### ISSUE TITLE
Rework calculator styling completely

### ISSUE THREAD

**Issue by guylev38** [guylev38/calculator#6]
As mentioned in #5 we need to rework the styling of the calculator.

**Comment by guylev38** [comment]
## TODO
 - [ ] Add shrinking and darkening effect to buttons on hover.
 - [ ] Make buttons square.
 - [ ] Make the calculator square with box-shadow.
